[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Oxime-Biocatalysis"
authors = [{name = "Amit Singh", email = "amit.amit@uni-graz.at"}]
dynamic = ["version", "description"]
